Repository Azure/ms-rest-js, pull requests merged in 2018-08, with the labels that each got.

#181 Add "sideEffects": false for webpack 4
  package.json
Labels: in progress

#184 RequestPolicyCreator -> RequestPolicyFactory
  Changelog.md
  lib/msRest.ts
  lib/policies/deserializationPolicy.ts
  lib/policies/exponentialRetryPolicy.ts
  lib/policies/generateClientRequestIdPolicy.ts
  lib/policies/logPolicy.ts
  lib/policies/msRestUserAgentPolicy.ts
  lib/policies/redirectPolicy.ts
  lib/policies/requestPolicy.ts
  lib/policies/rpRegistrationPolicy.ts
  lib/policies/signingPolicy.ts
  lib/policies/systemErrorRetryPolicy.ts
  lib/serviceClient.ts
  package.json
  samples/node-sample.ts
  test/shared/policies/deserializationPolicyTests.ts
  test/shared/serviceClientTests.ts
Labels: in progress

#189 Export TransferProgressEvent from msRest.ts
  lib/msRest.ts
Labels: in progress

#191 Add base HttpResponse
  lib/httpOperationResponse.ts
  lib/msRest.ts
  package.json
Labels: in progress

#193 Export AbortSignalLike
  lib/msRest.ts
Labels: in progress

#194 Various improvements to our script infrastructure
  .scripts/dependencies.js
  .scripts/dependencies.ts
  .scripts/latest.js
  .scripts/latest.ts
  .scripts/local.js
  .scripts/local.ts
  .scripts/preview.js
  .scripts/preview.ts
  .scripts/repository.ts
  package.json
Labels: Started-Sprint-123, Unplanned-Sprint-123, in progress

#187 Browser xml
  lib/msRest.ts
  lib/policies/deserializationPolicy.ts
  lib/serviceClient.ts
  lib/util/utils.ts
  lib/util/xml.browser.ts
  lib/util/xml.ts
  package-lock.json
  package.json
  webpack.config.ts
  webpack.testconfig.ts
Labels: in progress

#182 Typescript 3
  .scripts/unit.js
  lib/httpOperationResponse.ts
  lib/xhrHttpClient.ts
  package-lock.json
  package.json
  test/node/startTestServer.node.ts
  test/shared/defaultHttpClientTests.ts
Labels: in progress

#199 Headers fix
  lib/axiosHttpClient.ts
  lib/httpHeaders.ts
  lib/xhrHttpClient.ts
  test/browser/stub.browser.ts
  test/browser/xhrTests.browser.ts
Labels: in progress

#200 Change OperationSpec to be read only
  lib/operationSpec.ts
  lib/serviceClient.ts
Labels: in progress

#201 Changes needed for LRO support
  lib/axiosHttpClient.ts
  lib/msRest.ts
  lib/operationSpec.ts
  lib/policies/deserializationPolicy.ts
  lib/serviceClient.ts
  lib/webResource.ts
  lib/xhrHttpClient.ts
  test/shared/logFilterTests.ts
Labels: Planned-Sprint-122, Planned-Sprint-123, Started-Sprint-122, in progress

#202 Bump minor version due to LRO changes
  package-lock.json
  package.json
Labels: Planned-Sprint-123, Started-Sprint-123, in progress

#205 Add RestResponse type and more runtime deserialization features
  lib/axiosHttpClient.ts
  lib/httpOperationResponse.ts
  lib/msRest.ts
  lib/policies/deserializationPolicy.ts
  lib/policies/exponentialRetryPolicy.ts
  lib/restError.ts
  lib/serviceClient.ts
  lib/util/utils.ts
  lib/xhrHttpClient.ts
  package.json
  test/shared/defaultHttpClientTests.ts
  test/shared/serviceClientTests.ts
  test/shared/utilsTests.ts
Labels: in progress
