Repository Azure/ms-rest-js, pull requests merged in 2018-10, with the labels that each got.

#237 Add support for credentials to be a request policy
  lib/credentials/credentials.ts
  lib/serviceClient.ts
  lib/util/utils.ts
  package-lock.json
Labels: in progress

#238 Add URLBuilder.appendPath()
  lib/serviceClient.ts
  lib/url.ts
  test/shared/urlTests.ts
Labels: in progress

#239 Update User-Agent
  lib/policies/msRestUserAgentPolicy.ts
  test/node/userAgentFilterTests.node.ts
Labels: in progress

#240 Fix dependency problems
  lib/util/xml.browser.ts
  package-lock.json
  package.json
Labels: in progress

#242 move @types to devDependencies
  package-lock.json
  package.json
Labels: in progress

#243 Rollup
  .gitignore
  Changelog.md
  ThirdPartyNotices.txt
  index.html
  package-lock.json
  package.json
  rollup.config.js
  testserver/index.ts
  tsconfig.json
  webpack.config.ts
Labels: in progress

#248 Remove script step that changes package.json main property
  .scripts/dependencies.ts
  .scripts/latest.ts
  .scripts/local.ts
  .scripts/preview.ts
Labels: Started-Sprint-125, Unplanned-Sprint-125, in progress

#249 Update regular expressions to be non-greedy
  .scripts/dependencies.ts
Labels: Planned-Sprint-125, Started-Sprint-125, in progress

#250 Make xml parsing more consistent and add tests
  .gitignore
  lib/policies/deserializationPolicy.ts
  lib/serviceClient.ts
  lib/util/xml.browser.ts
  lib/util/xml.ts
  package-lock.json
  test/msAssert.ts
  test/shared/policies/deserializationPolicyTests.ts
  test/shared/xmlTests.ts
Labels: Started-Sprint-125, Unplanned-Sprint-125, in progress

#251 Ignore XML headers when deserializing XML elements with headers and text
  .vscode/launch.json
  lib/serializer.ts
  test/shared/policies/deserializationPolicyTests.ts
Labels: Started-Sprint-125, Unplanned-Sprint-125, in progress

#252 Add browser telemetry
  .gitignore
  lib/msRest.ts
  lib/policies/msRestUserAgentPolicy.browser.ts
  lib/policies/msRestUserAgentPolicy.stub.ts
  lib/policies/msRestUserAgentPolicy.ts
  lib/policies/userAgentPolicy.ts
  lib/serviceClient.ts
  package.json
  test/browser/msRestUserAgentPolicyTests.ts
  test/node/msRestUserAgentPolicyTests.ts
  test/node/userAgentFilterTests.node.ts
  webpack.testconfig.ts
Labels: in progress
