Repository Azure/ms-rest-js, pull requests merged in 2018-11, with the labels that each got.

#256 Fix missing renaming in ServiceClient
  lib/operationArguments.ts
  lib/serviceClient.ts
  test/shared/serviceClientTests.ts
Labels: Started-Sprint-126, Unplanned-Sprint-126, in progress

#258 Fix deserializing nested composite types with no polymorphic discriminator specified
  lib/serializer.ts
  test/shared/serializationTests.ts
Labels: in progress

#262 Fix (de)serializing polymorphic elements in an array
  lib/serializer.ts
  test/shared/serializationTests.ts
Labels: in progress

#259 Fix the issue of "Initializers are not allowed in ambient contexts" for 3.0.x version of TS
  lib/restError.ts
  package.json
Labels: in progress

#265 Rename NPM package to @azure/ms-rest-js
  Changelog.md
  package.json
Labels: Unplanned-Sprint-126, in progress

#267 Add Azure pipelines configuration
  azure-pipelines.yml
Labels: Unplanned-Sprint-126, in progress

#271 Update README.md to include build badge
  README.md
Labels: Unplanned-Sprint-126, in progress

#272 Change import from "msRest" in userAgentPolicy
  lib/policies/userAgentPolicy.ts
Labels: Started-Sprint-127, Unplanned-Sprint-127, in progress

#269 Build matrix
  .scripts/unit.js
  azure-pipelines-job.yml
  azure-pipelines.yml
  package.json
  test/node/startTestServer.node.ts
  test/shared/defaultHttpClientTests.ts
Labels: in progress

#274 Add better sourcemap support for debugging
  Changelog.md
  package.json
  rollup.config.js
Labels: Planned-Sprint-127, Started-Sprint-127, in progress

#275 Add GitHub-related configuration
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Unplanned-Sprint-127, in progress

#277 Add throttle handling policy
  lib/policies/throttlingRetryPolicy.ts
  lib/serviceClient.ts
  lib/util/constants.ts
  lib/webResource.ts
  package.json
  test/shared/policies/throttlingRetryPolicyTests.ts
Labels: Planned-Sprint-127, Started-Sprint-127, in progress

#279 Add throttling-related documentation
  lib/policies/throttlingRetryPolicy.ts
Labels: in progress

#278 Add 'no-return-await' TSLint rule
  tslint.json
Labels: in progress

#282 Fix rollup browser aliasing
  package.json
  rollup.config.js
Labels: Planned-Sprint-127, Started-Sprint-127, in progress

#283 Make unit tests stable
  .scripts/unit.js
  .scripts/unit.ts
  .vscode/launch.json
  package.json
  test/node/startTestServer.node.ts
  test/shared/defaultHttpClientTests.ts
  testserver/index.ts
Labels: Started-Sprint-127, Unplanned-Sprint-127, in progress

#285 Upgrade all dependencies
  package.json
  test/browser/msRestUserAgentPolicyTests.ts
  test/node/msRestUserAgentPolicyTests.ts
  test/shared/credentialTests.ts
  test/shared/defaultHttpClientTests.ts
  test/shared/serializationTests.ts
Labels: in progress

#287 Update dependencies.ts with latest changes from ms-rest-azure-js
  .scripts/dependencies.ts
  .scripts/preview.ts
  package.json
Labels: Started-Sprint-127, Unplanned-Sprint-127, in progress
