Repository Azure/ms-rest-js, pull requests merged in 2018-12, with the labels that each got.

#289 Add deserializing missing properties
  lib/serializer.ts
  package.json
  test/shared/serializationTests.ts
Labels: in progress

#291 Fix incorrect browser telemetry settings
  package.json
Labels: in progress

#294 Extract dependencies-related scripts to an external package
  .scripts/dependencies.ts
  .scripts/latest.ts
  .scripts/local.ts
  .scripts/repository.ts
  package.json
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#292 Remove const enums
  lib/url.ts
  package.json
Labels: Started-Sprint-128, Unplanned-Sprint-128, customer-reported, in progress

#295 Add test results to pipeline
  .gitignore
  azure-pipelines-job.yml
  package.json
  test/mocha.opts
Labels: Started-Sprint-128, Unplanned-Sprint-128, in progress

#296 Enable test coverage reporting
  .gitignore
  .scripts/unit.ts
  azure-pipelines-job.yml
  mocha.config.json
  package.json
  test/mocha.opts
Labels: Started-Sprint-128, Unplanned-Sprint-128, in progress

#297 Update test result and code coverage paths
  azure-pipelines-job.yml
Labels: Started-Sprint-128, Unplanned-Sprint-128, in progress

#299 Add package.json version check
  .scripts/checkPackageJsonVersion.ts
  azure-pipelines.yml
  package.json
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#300 Remove yargs dependencies, update version to 1.2.4
  package.json
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#301 Fix dependencies scripts
  .scripts/latest.ts
  .scripts/local.ts
  package.json
Labels: Started-Sprint-128, Unplanned-Sprint-128, in progress

#302 Add only() check
  .scripts/checkTestsForOnly.ts
  azure-pipelines.yml
  package.json
Labels: Started-Sprint-128, Unplanned-Sprint-128, in progress

#303 Add checkEverything.ts
  .scripts/checkEverything.ts
  .scripts/checkForOnlyCalls.ts
  .scripts/checkPackageJsonVersion.ts
  .scripts/checkTestsForOnly.ts
  azure-pipelines.yml
  package.json
Labels: Started-Sprint-128, Unplanned-Sprint-128, in progress

#307 Fix serialization bug for ie11
  lib/serializer.ts
  package.json
  test/shared/serializationTests.ts
Labels: Started-Sprint-129, Unplanned-Sprint-129, in progress
