Repository Azure/ms-rest-js, pull requests merged in 2019-01, with the labels that each got.

#313 Allow ServiceClientOptions.userAgent property to be a function
  Changelog.md
  lib/serviceClient.ts
  lib/util/constants.ts
  package.json
  test/shared/serviceClientTests.ts
Labels: Started-Sprint-130, Unplanned-Sprint-130, in progress

#314 Allow ServiceClientOptions.requestPolicyFactories to be a function
  .scripts/checkConstantsVersion.ts
  .scripts/checkEverything.ts
  azure-pipelines.yml
  lib/serviceClient.ts
  lib/util/constants.ts
  package.json
  test/shared/serviceClientTests.ts
Labels: Planned-Sprint-130, Started-Sprint-130, in progress

#316 Add karma for browser tests
  .gitignore
  .typings/karma.d.ts
  .typings/rollup-plugin-alias.d.ts
  .typings/rollup-plugin-commonjs.d.ts
  .typings/rollup-plugin-json.d.ts
  .typings/rollup-plugin-multi-entry.d.ts
  .typings/rollup-plugin-node-resolve.d.ts
  .typings/rollup-plugin-sourcemaps.d.ts
  .typings/rollup-plugin-visualizer.d.ts
  karma.conf.ts
  lib/util/constants.ts
  package.json
  rollup.config.js
  rollup.config.ts
  test/browser/msRestUserAgentPolicyTests.ts
  test/credentialTests.ts
  test/data/TestClient/lib/models/mappers.ts
  test/data/TestClient/lib/testClient.ts
  test/defaultHttpClientTests.ts
  test/logFilterTests.ts
  test/mocha.opts
  test/msAssert.ts
  test/msRestUserAgentPolicyTests.ts
  test/node/msRestUserAgentPolicyTests.ts
  test/operationParameterTests.ts
  test/policies/deserializationPolicyTests.ts
  test/policies/throttlingRetryPolicyTests.ts
  test/serializationTests.ts
  test/serviceClientTests.ts
  test/testUtils.ts
  test/urlTests.ts
  test/xhrTests.browser.ts
  test/xmlTests.ts
  webpack.testconfig.ts
Labels: in progress

#315 Add support for HTTP proxy
  lib/axiosHttpClient.ts
  lib/policies/proxyPolicy.ts
  lib/serviceClient.ts
  lib/util/constants.ts
  lib/webResource.ts
  lib/xhrHttpClient.ts
  package.json
  test/policies/proxyPolicyTests.ts
  test/xhrTests.browser.ts
Labels: in progress

#319 Update changelog for version 1.4.0-1.5.0
  Changelog.md
Labels: in progress

#321 Fix default HTTP client tests
  .scripts/checkEverything.ts
  karma.conf.ts
  lib/axiosHttpClient.ts
  lib/util/constants.ts
  mocha.config.json
  package.json
  test/defaultHttpClientTests.ts
  test/mockHttp.ts
  testserver/index.ts
  tsconfig.json
  webpack.testconfig.ts
Labels: Planned-Sprint-130, in progress

#322 Add HTTP(S) over HTTP(S) proxy support
  lib/axiosHttpClient.ts
  lib/policies/proxyPolicy.ts
  lib/serviceClient.ts
  package.json
  rollup.config.ts
  test/axiosHttpClientTests.node.ts
  test/defaultHttpClientTests.ts
  test/mockHttp.ts
  test/policies/proxyPolicyTests.ts
  test/serializationTests.ts
  test/serviceClientTests.ts
  webpack.testconfig.ts
Labels: Planned-Sprint-130, in progress

#323 Fix tunnel types are missing
  lib/axiosHttpClient.ts
  lib/util/constants.ts
  package.json
Labels: in progress

#328 Fix including proxy policy in browser
  lib/policies/proxyPolicy.browser.ts
  lib/util/constants.ts
  package.json
  rollup.config.ts
  test/msAssert.ts
  test/msRestUserAgentPolicyTests.ts
  test/policies/proxyPolicyTests.ts
  webpack.testconfig.ts
Labels: in progress
